name: flamenco_remote
description: "A Flamenco Render Farm Remote Controller"
publish_to: 'none'
version: 0.2.1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  device_preview: ^1.2.0
  http: ^1.2.2
  flutter_svg: ^2.0.16
  image_picker: ^1.1.2
  shared_preferences: ^2.3.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/brand.svg
